### ISSUE TITLE
Namespace not provided through map or generator

### ISSUE THREAD

**Issue by Thaoden** [mganss/XmlSchemaClassGenerator#13]
I try to translate a .xsd file to a .cs file, but I get the error message:
>Unhandled Exception: System.Exception: Namespace http://myNamespace/StandardLdapSchema.xsd not provided through map or generator.
   at XmlSchemaClassGenerator.Generator.BuildNamespace(Uri source, String xmlNamespace)
   at XmlSchemaClassGenerator.Generator.CreateNamespaceModel(Uri source, XmlQualifiedName qualifiedName)
   at XmlSchemaClassGenerator.Generator.CreateTypeModel(Uri source, XmlSchemaAnnotated type, XmlQualifiedName qualifiedN
ame)
   at XmlSchemaClassGenerator.Generator.BuildModel()
   at XmlSchemaClassGenerator.Generator.Generate(IEnumerable`1 files)
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args)

It is probably due to the import:

    <xs:schema attributeFormDefault="unqualified"
               elementFormDefault="qualified"
               xmlns:xs="http://www.w3.org/2001/XMLSchema"
               xmlns:att="http://myNamespace/Attributes.xsd"
               xmlns:ldap="http://myNamespace/StandardLdapSchema.xsd"
               targetNamespace="http://myNamespace/UtLdapSchema.xsd"
               xmlns="http://myNamespace/UtLdapSchema.xsd"
               >
      <xs:import schemaLocation="StandardLdapSchema.xsd" namespace="http://myNamespace/StandardLdapSchema.xsd" />
    (...)
    </xs:schema>

Is there a way I can fix this?

**Comment by mganss** [comment]
You can specify the C# namespace an XML Schema namespace should be mapped to on the command line like this:

```
XmlSchemaClassGenerator.Console.exe -nhttp://myNamespace/StandardLdapSchema.xsd=StandardLdapSchema file.xsd
```

In this example, the target C# namespace is `StandardLdapSchema`. Specify one `-n` option for each namespace to be mapped.
