### ISSUE TITLE
System.ArgumentException: Namespace "" not provided through map or generator

### ISSUE THREAD

**Issue by Nadare2012** [mganss/XmlSchemaClassGenerator#223]
I can't generate .cs file for schema below:
[AS_ADDR.OBJ.DIVISION_2_251_19_04_01_01.xsd.zip](https://github.com/mganss/XmlSchemaClassGenerator/files/5173941/AS_ADDR.OBJ.DIVISION_2_251_19_04_01_01.xsd.zip)

Command line arguments: xscgen AS_ADDR.OBJ.DIVISION_2_251_19_04_01_01.xsd

Trace:

```
Unhandled exception. System.ArgumentException: Namespace  not provided through map or generator.
   at XmlSchemaClassGenerator.ModelBuilder.BuildNamespace(Uri source, String xmlNamespace) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\ModelBuilder.cs:line 935
   at XmlSchemaClassGenerator.ModelBuilder.CreateNamespaceModel(Uri source, XmlQualifiedName qualifiedName) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\ModelBuilder.cs:line 793
   at XmlSchemaClassGenerator.ModelBuilder.CreateTypeModel(Uri source, XmlSchemaAnnotated type, XmlQualifiedName qualifiedName) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\ModelBuilder.cs:line 250
   at XmlSchemaClassGenerator.ModelBuilder.CreateElements(IEnumerable`1 elements) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\ModelBuilder.cs:line 182
   at XmlSchemaClassGenerator.ModelBuilder..ctor(GeneratorConfiguration configuration, XmlSchemaSet set) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\ModelBuilder.cs:line 63
   at XmlSchemaClassGenerator.Generator.Generate(XmlSchemaSet set) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\Generator.cs:line 283
   at XmlSchemaClassGenerator.Generator.Generate(IEnumerable`1 files) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\Generator.cs:line 275
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator.Console\Program.cs:line 209
```

Perhaps the problem can be solved with adding --namespace argument, but Exception message doesn't tell what namespace to provide.

Xsd.exe works fine.

**Comment by mganss** [comment]
It's the empty namespace (notice the two spaces after Namespace in the message). So using `-n=Empty` should work (replace `Empty` with whatever suits your project if you want).

**Comment by Nadare2012** [comment]
When I added -n=Empty argument (xscgen -n=Empty AS_ADDR.OBJ.TYPES_2_251_03_04_01_01.xsd) I got different exception:

```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at XmlSchemaClassGenerator.CodeUtilities.ParseNamespace(String nsArg, String namespacePrefix) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\CodeUtilities.cs:line 367
   at XmlSchemaClassGenerator.Console.Program.<>c__DisplayClass0_0.<Main>b__0(String n) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator.Console\Program.cs:line 154
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at XmlSchemaClassGenerator.EnumerableExtensions.ToNamespaceProvider(IEnumerable`1 items, GenerateNamespaceDelegate generate) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\EnumerableExtensions.cs:line 18
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator.Console\Program.cs:line 154

```

**Comment by Nadare2012** [comment]
Ah, I got it, -n =Empty (space between "-n" and "=") solves problem.

**Comment by mganss** [comment]
@Nadare2012 Oops, sorry for that. Glad it works now.
