### ISSUE TITLE
System.PlatformNotSupportedException is the generator creating class attributes not supported by XmlSerializer?

### ISSUE THREAD

**Issue by Cloudfare123** [mganss/XmlSchemaClassGenerator#240]
I have managed to generate a hundreds of classes using this tool which is a very good, but from looks of things it maybe using some Attributes which are not supported so this could prove a big blocker from going forward with it as there are to many classes to manually change. I did have to fix several compile time errors which was fine regarding wrong implementations of interfaces (collections etc). 

The main class "PublicationDeliveryStructure" which is generated from the NetEx schemas does not seem to load. http://netex.uk/netex/schema.htm 

XmlSerializer xmlSerializer = **new XmlSerializer(typeof(PublicationDeliveryStructure));**
netExObjectModel = (PublicationDeliveryStructure)xmlSerializer.Deserialize(streamReader);

System.PlatformNotSupportedException
  HResult=0x80131539
  Message=Compiling JScript/CSharp scripts is not supported
  Source=System.Private.Xml
  StackTrace:
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace, String location)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type)
   at NeTEx.NetExSerializer.DeserializeToFlowbirdNetExObjectModel(Byte[] netExContent) in \NeTEx\NetExSerializer.cs:line 21
   at Test.NetExSerializerTests.TestLoading_Netex_Bus_SimpleFares_PointToPoint_SingleProduct() in NetExSerializerTests.cs:line 24

**Comment by mganss** [comment]
I have made some changes to fix issues that prevent the netex schema to deserialize in 2.0.484. I successfully generated code for  `NeTEx_publication.xsd` that compiles and deserializes the example file `Netex_calendarCodeing_02.xml`. Please try the options `-sg` and `-r`. The former causes separate properties to be created for substituted elements and the latter causes the `Order` property to be set on the `XmlElementAttribute` which is necessary because the schema contains duplicate elements across inheritance hierarchies.

In my tests the specific exception you describe didn't occur but I've encountered it before, too (see https://github.com/mganss/XmlSchemaClassGenerator/issues/216#issuecomment-664517197).

If this still occurs with the latest version, please attach a demo XML here and report which command line options you have used to generate and which .NET target you are using.

**Comment by Cloudfare123** [comment]
Thanks for release 2.0.484. See you've generated classes without issues. I keep getting PlatformNotSupport in XmlSerializer(...)

Interested to know how you generated the classes. What setup you had, perhaps you have used more options or different setup? I'm on Net Core 3.1 or .Net standard 2 in testing so far with classes generated etc.

XmlSchemaClassGenerator.Console.exe -sg -r NeTEx_publication.xsd

20+ compile errors did you get these also?

Severity Code Description Project File Line Suppression State
Error CS0738 'SubscriptionTerminatedNotificationStructure' does not implement interface member 'ISubscriptionIdentifierResourcePropertyGroup.SubscriberRef'. 'SubscriptionTerminatedNotificationStructure.SubscriberRef' cannot implement 'ISubscriptionIdentifierResourcePropertyGroup.SubscriberRef' because it does not have the matching return type of 'ParticipantRefStructure'. NeTEx_484\NeTEx-484\Models\Siri.cs 4541 Active

**Comment by mganss** [comment]
I have used the following options and get no compilation errors: `-0 -v -r -sg -t-`. The options `-0` and `-v` are not strictly necessary. The option `-t-` turns off generation of interfaces which is necessary for the generated files to compile. 

I've made some further changes in 2.0.486 to better support group references but without `-t-` there still remain a couple of compilation errors. This is because in this schema group references change the value of `maxOccurs` which causes a collection property to be generated in the implementation class while the interface contains only a singular property (`maxOccurs="1"`).

My test application is a .NET Core 3.1 console application.

**Comment by Cloudfare123** [comment]
Great stuff works well with those options.  Although we are still doing some testing around example data going missing during importing and then output through the models.

**Comment by mganss** [comment]
I've made some further improvements for substitution groups in 2.0.487. Hopefully now you won't see any missing data. If you do, please attach a demo XML.

I've also found the root cause of the `System.PlatformNotSupportedException`. It's https://github.com/dotnet/runtime/issues/46196. This doesn't occur in the Netex schema (anymore) but there are others where it does (e.g. aixm, see #216).

**Comment by ac931274** [comment]
[Schema.zip](https://github.com/mganss/XmlSchemaClassGenerator/files/6097766/Schema.zip)
Hi there, 
I am also getting this problem.  I have a netStandard2.0 library project that uses the attached schemas.  The code is generated with the following script which is run as part of the pre build script:
dotnet xscgen -o generated -n "urn:ietf:params:xml:ns:eppcom-1.0=FoxHillSolutions.Escrow.eppcom" -n "urn:ietf:params:xml:ns:rdeDomain-1.0=FoxHillSolutions.Escrow.rdeDomain" -n "urn:ietf:params:xml:ns:rdeHeader-1.0=FoxHillSolutions.Escrow.rdeHeader" -n "urn:ietf:params:xml:ns:rdeHost-1.0=FoxHillSolutions.Escrow.rdeHost" -n "urn:ietf:params:xml:ns:rdeIDN-1.0=FoxHillSolutions.Escrow.rdeIDN" -n "urn:ietf:params:xml:ns:rdeRegistrar-1.0=FoxHillSolutions.Escrow.Registrar" -n "urn:ietf:params:xml:ns:rdeDnrdCommon-1.0=FoxHillSolutions.Escrow.DnrdCommon" -n "urn:ietf:params:xml:ns:secDNS-1.1=FoxHillSolutions.Escrow.secDNS" -n "urn:ietf:params:xml:ns:domain-1.0=FoxHillSolutions.Escrow.domain" -n "urn:ietf:params:xml:ns:contact-1.0=FoxHillSolutions.Escrow.contact" -n "urn:ietf:params:xml:ns:host-1.0=FoxHillSolutions.Escrow.host" -n "urn:ietf:params:xml:ns:rgp-1.0=FoxHillSolutions.Escrow.rgp" -n "urn:ietf:params:xml:ns:epp-1.0=FoxHillSolutions.Escrow.epp" -n "urn:ietf:params:xml:ns:rde-1.0=FoxHillSolutions.Escrow.rde" -n "urn:ietf:params:xml:ns:rdeContact-1.0=FoxHillSolutions.Escrow.rdeContact" -n "urn:ietf:params:xml:ns:rdeEppParams-1.0=FoxHillSolutions.Escrow.rdeEppParams" -n "urn:ietf:params:xml:ns:rdeNNDN-1.0=FoxHillSolutions.Escrow.rdeNNDN" -n "urn:ietf:params:xml:ns:rdePolicy-1.0=FoxHillSolutions.Escrow.rdePolicy" .\Schema\*.xsd -t- -c -sg

 I get the error when I create the serializer (in a netCore3.1 test project) with the command:
            var baseType = typeof(FoxHillSolutions.Escrow.rde.EscrowDepositType);
            var s = new XmlSerializer(baseType);

I did not use the -r option as it created an attribute which the compiler says does not take the Order option:
        [System.Xml.Serialization.XmlAnyAttributeAttribute(Order=1)]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute> AnyAttribute

I am using xscgen Version 2.0.502.0

Thanks for the great tool and any indications on what I am doing wrong or what I could do if this is an issue that is not to do with xscgen.

**Comment by mganss** [comment]
@ac931274 This issue occurs because the schema contains the same type name (such as `DeleteType`) in more than one namespace and collections of more than one of these types are used within an element. For example, the type `DeletesType` has collections of 6 different types all named `DeleteType` from distinct namespaces. This triggers https://github.com/dotnet/runtime/issues/46196.

I've added the `--un` option in 2.0.509. If it's enabled xscgen will generate type names that are unique even across namespaces, working around https://github.com/dotnet/runtime/issues/46196 which won't be fixed until .NET 6.0.

**Comment by ac931274** [comment]
Thank you,  I have just downloaded the update and can confirm that this is fixed.  If you're ever in Birmingham, UK, I'll buy you a drink :)
