### ISSUE TITLE
Unhandled exception with version 2.0.488

### ISSUE THREAD

**Issue by emaschas** [mganss/XmlSchemaClassGenerator#243]
I get an unhandled exception with the 2.0.488 version with a file that was processed correctly with version 2.0.486.
The file (visinfo.xsd) is available here : 
https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Schemas/version.xsd
and the message is:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at XmlSchemaClassGenerator.DocumentationModel.<>c__DisplayClass13_1.<AddDescription>b__1(String l) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\TypeModel.cs:line 89
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at XmlSchemaClassGenerator.DocumentationModel.<>c__DisplayClass13_0.<AddDescription>b__0(DocumentationModel d) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\TypeModel.cs:line 89
   at System.Linq.Enumerable.WhereListIterator`1.GetCount(Boolean onlyIfCheap)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at XmlSchemaClassGenerator.DocumentationModel.GetSingleDoc(IEnumerable`1 docs) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\TypeModel.cs:line 101
   at XmlSchemaClassGenerator.DocumentationModel.AddDescription(CodeAttributeDeclarationCollection attributes, IEnumerable`1 docs, GeneratorConfiguration conf) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\TypeModel.cs:line 89
   at XmlSchemaClassGenerator.PropertyModel.AddDocs(CodeTypeMember member) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\TypeModel.cs:line 762
   at XmlSchemaClassGenerator.PropertyModel.AddMembersTo(CodeTypeDeclaration typeDeclaration, Boolean withDataBinding) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\TypeModel.cs:line 940
   at XmlSchemaClassGenerator.ClassModel.Generate() in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\TypeModel.cs:line 440
   at XmlSchemaClassGenerator.NamespaceModel.Generate(String namespaceName, IEnumerable`1 parts, GeneratorConfiguration conf) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\TypeModel.cs:line 44
   at XmlSchemaClassGenerator.ModelBuilder.<GenerateCode>b__33_2(NamespaceHierarchyItem nhi) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\ModelBuilder.cs:line 1014
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at XmlSchemaClassGenerator.Generator.Generate(XmlSchemaSet set) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator\Generator.cs:line 310
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator.Console\Program.cs:line 211
```

**Comment by mganss** [comment]
Fixed in 2.0.490.
