### ISSUE TITLE
Duplicate XML element when generating for musicxml

### ISSUE THREAD

**Issue by QiuFeng54321** [mganss/XmlSchemaClassGenerator#315]
This is part of musicxml.xsd from [here](https://github.com/w3c/musicxml/releases/tag/v4.0):
```xml
	<xs:complexType name="part-list">
		<xs:annotation>
			<xs:documentation>The part-list identifies the different musical parts in this document. Each part has an ID that is used later within the musical data. Since parts may be encoded separately and combined later, identification elements are present at both the score and score-part levels. There must be at least one score-part, combined as desired with part-group elements that indicate braces and brackets. Parts are ordered from top to bottom in a score based on the order in which they appear in the part-list.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:group ref="part-group" minOccurs="0" maxOccurs="unbounded"/>
			<xs:group ref="score-part"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group ref="part-group"/>
				<xs:group ref="score-part"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
```
  
I used command arguments`-o out/ --collectionSettersMode=Public --nc --nu -n "=MusicXml" <pathto>/musicxml.xsd`.  
This generated collections `Part_Group` and `Part_Group_2`, which throws this when trying to deserialize:
```
...
---> System.InvalidOperationException: There was an error reflecting property 'Part_Group_2'.
 ---> System.InvalidOperationException: The XML element 'part-group' from namespace '' is already present in the current scope. Use XML attributes to specify another XML name or namespace for the element.
   at System.Xml.Serialization.XmlReflectionImporter.AddUniqueAccessor(INameScope scope, Accessor accessor)
   at System.Xml.Serialization.XmlReflectionImporter.AddUniqueAccessor(MemberMapping member, INameScope elements, INameScope attributes, Boolean isSequence)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
...
```
using
```c#
var serializer = new XmlSerializer(typeof(Score_Partwise));
var xml = serializer.Deserialize(new FileStream(path, FileMode.Open)) as Score_Partwise;
```

I'm rather new to this so I have no idea how to resolve this problem.

**Comment by mganss** [comment]
I have a feeling this occurs because of the way choice elements are handled. I won't be able to investigate in more detail until next week, though.
