### ISSUE TITLE
Generator fails when dealing with infinite floats

### ISSUE THREAD

**Issue by diredev** [mganss/XmlSchemaClassGenerator#327]
The schema I'm trying to import uses infinite float or double values as defaults. Here's a very basic example:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example.com/test">
    <xs:element name="Root">
        <xs:complexType>
            <xs:attribute name="value" type="xs:double" use="optional" default="INF"/>
        </xs:complexType>
    </xs:element>
</xs:schema>
```

Trying to import this file using the Generator will always result in the following error:

```
Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToDouble(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at XmlSchemaClassGenerator.SimpleModel.GetDefaultValueFor(String defaultString, Boolean attribute)
   at XmlSchemaClassGenerator.PropertyModel.AddMembersTo(CodeTypeDeclaration typeDeclaration, Boolean withDataBinding)
   at XmlSchemaClassGenerator.ClassModel.Generate()
   at XmlSchemaClassGenerator.NamespaceModel.Generate(String namespaceName, IEnumerable`1 parts, GeneratorConfiguration conf)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at XmlSchemaClassGenerator.Generator.Generate(XmlSchemaSet set)
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args)
```

----

This is likely caused by a difference in sematics:

XML Schema uses the constants `INF` and `-INF` to denote floating point infinity, whereas .NET uses `Infinity` and `-Infinity` (when using the `InvariantCulture`). Note that `NaN` isn't affected, since both languages use the same constant for that one.

Also note that the actual constants used should in fact be customizable through `NumberFormatInfo.PositiveInfinitySymbol` and `NumberFormatInfo.NegativeInfinitySymbol`, which might be worth looking into...

**Comment by mganss** [comment]
Thanks for reporting this. The string value used by .NET when converting from double to string and vice versa is irrelevant for our use case, since we can use the statically typed constants `double.NegativeInfinity` and `double.PositiveInfinity`.

```c#
[global::System.Xml.Serialization.XmlIgnoreAttribute()]
private double _defaultDoubleInf = double.NegativeInfinity;

[global::System.ComponentModel.DefaultValueAttribute(double.NegativeInfinity)]
[global::System.Xml.Serialization.XmlElementAttribute("defaultDoubleInf")]
public double DefaultDoubleInf
{
    get
    {
        return this._defaultDoubleInf;
    }
    set
    {
        this._defaultDoubleInf = value;
    }
}
```
