### ISSUE TITLE
Error in trying to replace default collection type

### ISSUE THREAD

**Issue by dodyg** [mganss/XmlSchemaClassGenerator#47]
What is the proper way to replace the collection type used in the generated code?

```dotnet XmlSchemaClassGenerator.Console.dll *.xsd -o output -n http://www.iata.org/IATA/EDIST/2017.2=IATA -v -ct Systems.Collections.Generic.List```

generates 

```
Unhandled Exception: System.TypeLoadException: Could not load type 'Systems.Collections.Generic.List' from assembly 'XmlSchemaClassGenerator.Console, Version=2.0.82.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at XmlSchemaClassGenerator.Console.Program.<>c__DisplayClass0_0.<Main>b__13(String v) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator.Console\Program.cs:line 74
   at Mono.Options.Option.Invoke(OptionContext c) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator.Console\Mono.Options\Options.cs:line 616
   at Mono.Options.OptionSet.Parse(String argument, OptionContext c) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator.Console\Mono.Options\Options.cs:line 1160
   at Mono.Options.OptionSet.Parse(IEnumerable`1 arguments) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator.Console\Mono.Options\Options.cs:line 1060
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args) in C:\projects\xmlschemaclassgenerator\XmlSchemaClassGenerator.Console\Program.cs:line 82
E:\ndc```

**Comment by mganss** [comment]
Use ``--ct System.Collections.Generic.List`1``. See also https://docs.microsoft.com/en-us/dotnet/api/system.type.gettype

**Comment by dodyg** [comment]
Thanks!

It probably better to give this as part of the readme example. If people wants to replace the default collection, the generic List will be the most obvious candidate.

**Comment by mganss** [comment]
You're right, I've added a section to the readme, although there's already an example right in the usage section 😉
