### ISSUE TITLE
Imported files are not processed correctly

### ISSUE THREAD

**Issue by datguy** [mganss/XmlSchemaClassGenerator#49]
I have several schemas that use shared types defined in another schema.  I can generate these with a single run of xsd.exe, but it doesn't provide some of the features I need.
```
> xsd -c -f shared.xsd main1.xsd main2.xsd
Writing file 'shared_main1_main2.cs'.
```

When I try the same thing with XmlSchemaClassGenerator, I get a variety of exceptions.  At first I thought it was a problem with two xsd files importing the same shared file, but then I tried it with just one of the main files.  The exception I get depends on which file I specify first:
```
>XmlSchemaClassGenerator.Console.exe shared.xsd main1.xsd
Unhandled Exception: System.Exception: Namespace main1 not provided through map or generator.
   at XmlSchemaClassGenerator.Generator.BuildNamespace(Uri source, String xmlNamespace)
   at XmlSchemaClassGenerator.Generator.CreateNamespaceModel(Uri source, XmlQualifiedName qualifiedName)
   at XmlSchemaClassGenerator.Generator.CreateTypeModel(Uri source, XmlSchemaAnnotated type, XmlQualifiedName qualifiedName)
   at XmlSchemaClassGenerator.Generator.BuildModel()
   at XmlSchemaClassGenerator.Generator.Generate(IEnumerable`1 files)
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args)


>XmlSchemaClassGenerator.Console.exe main1.xsd shared.xsd
Unhandled Exception: System.Xml.Schema.XmlSchemaException: The complexType 'Shared:sharedType' has already been declared.
   at System.Xml.Schema.XmlSchemaSet.InternalValidationCallback(Object sender, ValidationEventArgs e)
   at System.Xml.Schema.BaseProcessor.AddToTable(XmlSchemaObjectTable table, XmlQualifiedName qname, XmlSchemaObject item)
   at System.Xml.Schema.Compiler.Prepare(XmlSchema schema, Boolean cleanup)
   at System.Xml.Schema.XmlSchemaSet.Compile()
   at XmlSchemaClassGenerator.Generator.Generate(IEnumerable`1 files)
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args)
```

[shared.xsd](https://gist.github.com/datguy/4a32c3447919ce05bfa8341c8e63526b)
[main1.xsd](https://gist.github.com/datguy/24e4adaff2edd56ca838f55626fe7651)
[main2.xsd](https://gist.github.com/datguy/39568eb399488426671be28265ae188b)

**Comment by mganss** [comment]
The shared file must not be specified on the command line and you must specify identifiers for the main1 and main2 namespaces:
```
XmlSchemaClassGenerator.Console.exe main?.xsd -n main1=Main1 -n main2=Main2
```

The fact that you have to explicitly specify the namespace identifiers is due to a shortcoming in the code that autogenerates namespace identifiers AFAICT. I'll fix this shortly.
