### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by AnderssonPeter** [mganss/XmlSchemaClassGenerator#51]
I'm trying to use this project with the following xsd:
```xml
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="BaseCondition">
      <xs:attribute type="xs:string" name="name" use="optional"/>
      <xs:attribute type="xs:string" name="value" use="optional"/>
  </xs:complexType>
  <xs:complexType name="BaseGroup">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="EXISTS" type="BaseCondition" minOccurs="0" />
      <xs:element name="LT" type="BaseCondition" minOccurs="0"/>
      <xs:element name="LTE" type="BaseCondition" minOccurs="0"/>
      <xs:element name="GT" type="BaseCondition" minOccurs="0"/>
      <xs:element name="GTE" type="BaseCondition" minOccurs="0"/>
      <xs:element name="EQ" type="BaseCondition" minOccurs="0"/>
      <xs:element name="NE" type="BaseCondition" minOccurs="0"/>
      <xs:element name="LIKE" type="BaseCondition" minOccurs="0"/>
      <xs:element name="NOTLIKE" type="BaseCondition" minOccurs="0"/>
      <xs:element name="IN" type="BaseCondition" minOccurs="0"/>
      <xs:element name="NOTIN" type="BaseCondition" minOccurs="0"/>
      <xs:element name="WITHIN" type="BaseCondition" minOccurs="0"/>
      <xs:element name="AND" type="BaseGroup" minOccurs="0"/>
      <xs:element name="OR" type="BaseGroup" minOccurs="0"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="Login">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="authenticationkey"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Query">
    <xs:sequence>
      <xs:element name="FILTER" type="BaseGroup"/>
      <xs:element name="INCLUDE" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="objecttype"/>
    <xs:attribute type="xs:string" name="orderby"/>
  </xs:complexType>
  <xs:element name="REQUEST">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="LOGIN" type="Login"/>
        <xs:element name="QUERY" type="Query"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

and the following command line `XmlSchemaClassGenerator.Console.exe --namespace=Test Trafikverket.xsd` 

but i get the following error:
```bash
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at XmlSchemaClassGenerator.Console.Program.ParseNamespace(String nsArg, String namespacePrefix)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at XmlSchemaClassGenerator.EnumerableExtensions.ToNamespaceProvider(IEnumerable`1 items, GenerateNamespaceDelegate generate)
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args)
```

what am i doing wrong?

**Comment by mganss** [comment]
Admittedly, the command line syntax is a little convoluted. In order to provide a C# namespace name for an empty XML Schema namespace you have to do something like this:
```
XmlSchemaClassGenerator.Console.exe -n =Test Trafikverket.xsd
```
Note the space between `-n` and `=Test`.

**Comment by AnderssonPeter** [comment]
Thanks that did it!

**Comment by shawty** [comment]
Could you possibly add a note to this effect in the read-me.  I was just about to report this same error when I noticed this existing issue.

It would definately help your sanity if the readme notes stated, not doing this will throw, beacuse right off the bat this was the first exception I saw before I even got it to do anything, a lesser experienced person is going to instantly reach for the issues button :-)
