### ISSUE TITLE
Using '|' to map XML namespace to input file fails

### ISSUE THREAD

**Issue by goldsam** [mganss/XmlSchemaClassGenerator#61]
## Summary
I am using using XmlSchemaClassGenerator-beta version 2.0.106.

Following the documentation, I am trying to use the `|` character to delimit the XML namespace and the corresponding file. In my example this namepace/file is a dependency of the primary xsd document. This fails with an `System.Xml.Schema.XmlSchemaException` claiming the dependency type in the reference namespace/file is not declared.

## Minimal Reproducible Example:

`name.xsd` defines a `FullName` element representing a persons name. `contacts.xsd` defines an element 'Contacts' element which is list of `FullName` elements defined in the dependency `name.xsd` schema.

Command issued:
`.\dotnet-xscgen.exe -n "http://example.com/name|name.xsd=Example.Name" -n "http://example.com/contacts=Example.Contacts" contacts.xsd`

File `name.xsd`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://example.com/name"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://example.com/name" elementFormDefault="qualified">

  <xs:complexType name="FullName">
    <xs:sequence>
      <xs:element type="xs:string" name="GivenName" minOccurs="1" maxOccurs="1"/>
      <xs:element type="xs:string" name="FamilyName" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element type="FullName" name="FullName"></xs:element>
</xs:schema>
```

File `contacts.xsd`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://example.com/contacts"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:name="http://example.com/name"
           xmlns="http://example.com/contacts" elementFormDefault="qualified">

  <xs:complexType name="Contacts">
    <xs:sequence>
      <xs:element type="name:FullName" name="Contact" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element type="Contacts" name="Contacts"></xs:element>
</xs:schema>
```

Output:
```
Unhandled Exception: System.Xml.Schema.XmlSchemaException: Type 'http://example.com/name:FullName' is not declared.
   at System.Xml.Schema.XmlSchemaSet.InternalValidationCallback(Object sender, ValidationEventArgs e)
   at System.Xml.Schema.Compiler.CompileElement(XmlSchemaElement xe)
   at System.Xml.Schema.Compiler.CompileParticleElements(XmlSchemaComplexType complexType, XmlSchemaParticle particle)
   at System.Xml.Schema.Compiler.CompileParticleElements(XmlSchemaComplexType complexType, XmlSchemaParticle particle)
   at System.Xml.Schema.Compiler.CompileComplexTypeElements(XmlSchemaComplexType complexType)
   at System.Xml.Schema.Compiler.Compile()
   at System.Xml.Schema.Compiler.Execute(XmlSchemaSet schemaSet, SchemaInfo schemaCompiledInfo)
   at System.Xml.Schema.XmlSchemaSet.Compile()
   at XmlSchemaClassGenerator.Generator.Generate(IEnumerable`1 files)
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args)
```

**Comment by mganss** [comment]
The `|` syntax is for cases where you want to generate C# namespaces according to which xsd file a type is declared in. It is not for specifying input files. In your example, simply specify both `name.xsd` and `contacts.xsd` as input files like so:

```
dotnet-xscgen.exe -nhttp://example.com/name=Example.Name -nhttp://example.com/contacts=Example.Contacts contacts.xsd name.xsd
```

**Comment by mganss** [comment]
Added a new section to the README
