### ISSUE TITLE
Namespace not provided through map or generator

### ISSUE THREAD

**Issue by ratajgasper** [mganss/XmlSchemaClassGenerator#78]
Hi,

I'm trying to convert this .xsd to c# class... I get an exception when trying to convert it. i'm not an XML or XSD expert so I don't know what exactly am I looking for...

```
Unhandled Exception: System.Exception: Namespace http://www.w3.org/2000/09/xmldsig# not provided through map or generator.
   at XmlSchemaClassGenerator.ModelBuilder.BuildNamespace(Uri source, String xmlNamespace)
   at XmlSchemaClassGenerator.ModelBuilder.CreateNamespaceModel(Uri source, XmlQualifiedName qualifiedName)
   at XmlSchemaClassGenerator.ModelBuilder.CreateTypeModel(Uri source, XmlSchemaAnnotated type, XmlQualifiedName qualifiedName)
   at XmlSchemaClassGenerator.ModelBuilder..ctor(GeneratorConfiguration configuration, XmlSchemaSet set)
   at XmlSchemaClassGenerator.Generator.Generate(XmlSchemaSet set)
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args)
```

is there anything that can be done?
Thanks!

**Comment by mganss** [comment]
You must provide a mapping for the namespace on the command line, e.g. `-n http://www.w3.org/2000/09/xmldsig#=XmlDsig`. This will generate types from the XML namespace http://www.w3.org/2000/09/xmldsig# into the C# namespace `XmlDsig`.
